import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/libs/providers/next-theme-provider";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { twMerge } from "tailwind-merge";
import "./globals.css";
import AppStateProvider from "@/libs/providers/app-state-provider";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={twMerge("bg-background", dmSans.className)}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <AppStateProvider>
            <Toaster />
            {children}
          </AppStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
